/* Definitions for BOARD_BootClockRUN functional group */
/* ADCCLKDIV: DIV=0 */
#define BOARD_BOOTCLOCKRUN_SYSCON_ADCCLKDIV_INIT 0
/* ADCCLKSEL: SEL=0 */
#define BOARD_BOOTCLOCKRUN_SYSCON_ADCCLKSEL_INIT 0
/* CAPTCLKSEL: SEL=7 */
#define BOARD_BOOTCLOCKRUN_SYSCON_CAPTCLKSEL_INIT 0x7U
/* CLKOUTDIV: DIV=0 */
#define BOARD_BOOTCLOCKRUN_SYSCON_CLKOUTDIV_INIT 0
/* CLKOUTSEL: SEL=0 */
#define BOARD_BOOTCLOCKRUN_SYSCON_CLKOUTSEL_INIT 0
/* FRG0CLKSEL: SEL=0 */
#define BOARD_BOOTCLOCKRUN_SYSCON_FRG0CLKSEL_INIT 0
/* FRG0MULT: MULT=0 */
#define BOARD_BOOTCLOCKRUN_SYSCON_FRG0MULT_INIT 0
/* I2C0CLKSEL: SEL=1 */
#define BOARD_BOOTCLOCKRUN_SYSCON_I2C0CLKSEL_INIT 0x1U
/* I2C1CLKSEL: SEL=1 */
#define BOARD_BOOTCLOCKRUN_SYSCON_I2C1CLKSEL_INIT 0x1U
/* MAINCLKSEL: SEL=0 */
#define BOARD_BOOTCLOCKRUN_SYSCON_MAINCLKSEL_INIT 0
/* PDRUNCFG: LPOSC_PD=0, FRO_PD=0 */
#define BOARD_BOOTCLOCKRUN_SYSCON_PDRUNCFG_INIT 0xA038U
/* SPI0CLKSEL: SEL=7 */
#define BOARD_BOOTCLOCKRUN_SYSCON_SPI0CLKSEL_INIT 0x7U
/* SYSAHBCLKDIV: DIV=1 */
#define BOARD_BOOTCLOCKRUN_SYSCON_SYSAHBCLKDIV_INIT 0x1U
/* UART0CLKSEL: SEL=7 */
#define BOARD_BOOTCLOCKRUN_SYSCON_UART0CLKSEL_INIT 0x7U
/* UART1CLKSEL: SEL=7 */
#define BOARD_BOOTCLOCKRUN_SYSCON_UART1CLKSEL_INIT 0x7U
