/***********************************************************************************************************************
 * This file was generated by the MCUXpresso Config Tools. Any manual edits made to this file
 * will be overwritten if the respective MCUXpresso Config Tools is used to update this file.
 **********************************************************************************************************************/

#ifndef _PIN_MUX_H_
#define _PIN_MUX_H_

/***********************************************************************************************************************
 * Definitions
 **********************************************************************************************************************/

/*! @brief Direction type  */
typedef enum _pin_mux_direction
{
    kPIN_MUX_DirectionInput = 0U,        /* Input direction */
    kPIN_MUX_DirectionOutput = 1U,       /* Output direction */
    kPIN_MUX_DirectionInputOrOutput = 2U /* Input or output direction */
} pin_mux_direction_t;

/*!
 * @addtogroup pin_mux
 * @{
 */

/***********************************************************************************************************************
 * API
 **********************************************************************************************************************/

#if defined(__cplusplus)
extern "C" {
#endif

/*!
 * @brief Calls initialization functions.
 *
 */
void BOARD_InitBootPins(void);

#define IOCON_PIO_HYS_EN 0x20u      /*!<@brief Enable hysteresis */
#define IOCON_PIO_INV_DI 0x00u      /*!<@brief Input not invert */
#define IOCON_PIO_MODE_PULLUP 0x10u /*!<@brief Selects pull-up function */
#define IOCON_PIO_OD_DI 0x00u       /*!<@brief Disables Open-drain function */

/*! @name SWCLK (coord B1), swclk
  @{ */
/* Routed pin properties */
#define BOARD_INITPINS_swclk_PERIPHERAL SWD                    /*!<@brief Peripheral name */
#define BOARD_INITPINS_swclk_SIGNAL SWCLK                      /*!<@brief Signal name */
#define BOARD_INITPINS_swclk_PIN_NAME SWCLK                    /*!<@brief Routed pin name */
#define BOARD_INITPINS_swclk_LABEL "swclk"                     /*!<@brief Label */
#define BOARD_INITPINS_swclk_NAME "swclk"                      /*!<@brief Identifier */
#define BOARD_INITPINS_swclk_DIRECTION kPIN_MUX_DirectionInput /*!<@brief Direction */
#define BOARD_INITPINS_swclk_PORT 0U                           /*!<@brief PORT device index: 0 */
#define BOARD_INITPINS_swclk_PIN 3U                            /*!<@brief PORT pin number */
#define BOARD_INITPINS_swclk_PIN_MASK (1U << 3U)               /*!<@brief PORT pin mask */
                                                               /* @} */

/*! @name SWDIO (coord B2), swdio
  @{ */
/* Routed pin properties */
#define BOARD_INITPINS_swdio_PERIPHERAL SWD                    /*!<@brief Peripheral name */
#define BOARD_INITPINS_swdio_SIGNAL SWDIO                      /*!<@brief Signal name */
#define BOARD_INITPINS_swdio_PIN_NAME SWDIO                    /*!<@brief Routed pin name */
#define BOARD_INITPINS_swdio_LABEL "swdio"                     /*!<@brief Label */
#define BOARD_INITPINS_swdio_NAME "swdio"                      /*!<@brief Identifier */
#define BOARD_INITPINS_swdio_DIRECTION kPIN_MUX_DirectionInput /*!<@brief Direction */
#define BOARD_INITPINS_swdio_PORT 0U                           /*!<@brief PORT device index: 0 */
#define BOARD_INITPINS_swdio_PIN 2U                            /*!<@brief PORT pin number */
#define BOARD_INITPINS_swdio_PIN_MASK (1U << 2U)               /*!<@brief PORT pin mask */
                                                               /* @} */

/*! @name PIO0_10 (coord A2), i2c1_scl_dac
  @{ */
/* Routed pin properties */
#define BOARD_INITPINS_i2c1_scl_dac_PERIPHERAL I2C1                   /*!<@brief Peripheral name */
#define BOARD_INITPINS_i2c1_scl_dac_SIGNAL SCL                        /*!<@brief Signal name */
#define BOARD_INITPINS_i2c1_scl_dac_PIN_NAME PIO0_10                  /*!<@brief Routed pin name */
#define BOARD_INITPINS_i2c1_scl_dac_LABEL "i2c1_scl_dac"              /*!<@brief Label */
#define BOARD_INITPINS_i2c1_scl_dac_NAME "i2c1_scl_dac"               /*!<@brief Identifier */
#define BOARD_INITPINS_i2c1_scl_dac_DIRECTION kPIN_MUX_DirectionInput /*!<@brief Direction */
#define BOARD_INITPINS_i2c1_scl_dac_PORT 0U                           /*!<@brief PORT device index: 0 */
#define BOARD_INITPINS_i2c1_scl_dac_PIN 10U                           /*!<@brief PORT pin number */
#define BOARD_INITPINS_i2c1_scl_dac_PIN_MASK (1U << 10U)              /*!<@brief PORT pin mask */
                                                                      /* @} */

/*! @name PIO0_11 (coord A1), i2c1_sda_dac
  @{ */
/* Routed pin properties */
#define BOARD_INITPINS_i2c1_sda_dac_PERIPHERAL I2C1                   /*!<@brief Peripheral name */
#define BOARD_INITPINS_i2c1_sda_dac_SIGNAL SDA                        /*!<@brief Signal name */
#define BOARD_INITPINS_i2c1_sda_dac_PIN_NAME PIO0_11                  /*!<@brief Routed pin name */
#define BOARD_INITPINS_i2c1_sda_dac_LABEL "i2c1_sda_dac"              /*!<@brief Label */
#define BOARD_INITPINS_i2c1_sda_dac_NAME "i2c1_sda_dac"               /*!<@brief Identifier */
#define BOARD_INITPINS_i2c1_sda_dac_DIRECTION kPIN_MUX_DirectionInput /*!<@brief Direction */
#define BOARD_INITPINS_i2c1_sda_dac_PORT 0U                           /*!<@brief PORT device index: 0 */
#define BOARD_INITPINS_i2c1_sda_dac_PIN 11U                           /*!<@brief PORT pin number */
#define BOARD_INITPINS_i2c1_sda_dac_PIN_MASK (1U << 11U)              /*!<@brief PORT pin mask */
                                                                      /* @} */

/*! @name PIO0_1 (coord A4), i2c0_sda_host
  @{ */
/* Routed pin properties */
#define BOARD_INITPINS_i2c0_sda_host_PERIPHERAL I2C0                   /*!<@brief Peripheral name */
#define BOARD_INITPINS_i2c0_sda_host_SIGNAL SCL                        /*!<@brief Signal name */
#define BOARD_INITPINS_i2c0_sda_host_PIN_NAME PIO0_1                   /*!<@brief Routed pin name */
#define BOARD_INITPINS_i2c0_sda_host_LABEL "i2c0_sda_host"             /*!<@brief Label */
#define BOARD_INITPINS_i2c0_sda_host_NAME "i2c0_sda_host"              /*!<@brief Identifier */
#define BOARD_INITPINS_i2c0_sda_host_DIRECTION kPIN_MUX_DirectionInput /*!<@brief Direction */
#define BOARD_INITPINS_i2c0_sda_host_PORT 0U                           /*!<@brief PORT device index: 0 */
#define BOARD_INITPINS_i2c0_sda_host_PIN 1U                            /*!<@brief PORT pin number */
#define BOARD_INITPINS_i2c0_sda_host_PIN_MASK (1U << 1U)               /*!<@brief PORT pin mask */
                                                                       /* @} */

/*! @name PIO0_15 (coord A3), i2c0_scl_host
  @{ */
/* Routed pin properties */
#define BOARD_INITPINS_i2c0_scl_host_PERIPHERAL I2C0                   /*!<@brief Peripheral name */
#define BOARD_INITPINS_i2c0_scl_host_SIGNAL SDA                        /*!<@brief Signal name */
#define BOARD_INITPINS_i2c0_scl_host_PIN_NAME PIO0_15                  /*!<@brief Routed pin name */
#define BOARD_INITPINS_i2c0_scl_host_LABEL "i2c0_scl_host"             /*!<@brief Label */
#define BOARD_INITPINS_i2c0_scl_host_NAME "i2c0_scl_host"              /*!<@brief Identifier */
#define BOARD_INITPINS_i2c0_scl_host_DIRECTION kPIN_MUX_DirectionInput /*!<@brief Direction */
#define BOARD_INITPINS_i2c0_scl_host_PORT 0U                           /*!<@brief PORT device index: 0 */
#define BOARD_INITPINS_i2c0_scl_host_PIN 15U                           /*!<@brief PORT pin number */
#define BOARD_INITPINS_i2c0_scl_host_PIN_MASK (1U << 15U)              /*!<@brief PORT pin mask */
                                                                       /* @} */

/*! @name PIO0_14 (coord E3), dac_reset_in
  @{ */
/* Routed pin properties */
#define BOARD_INITPINS_dac_reset_in_PERIPHERAL LVLSHFT        /*!<@brief Peripheral name */
#define BOARD_INITPINS_dac_reset_in_SIGNAL IN                 /*!<@brief Signal name */
#define BOARD_INITPINS_dac_reset_in_CHANNEL 0                 /*!<@brief Signal channel */
#define BOARD_INITPINS_dac_reset_in_PIN_NAME PIO0_14          /*!<@brief Routed pin name */
#define BOARD_INITPINS_dac_reset_in_LABEL "dac_reset_in"      /*!<@brief Label */
#define BOARD_INITPINS_dac_reset_in_NAME "dac_reset_in"       /*!<@brief Identifier */
#define BOARD_INITPINS_dac_reset_in_PORT 0U                   /*!<@brief PORT device index: 0 */
#define BOARD_INITPINS_dac_reset_in_PIN 14U                   /*!<@brief PORT pin number */
#define BOARD_INITPINS_dac_reset_in_PIN_MASK (1U << 14U)      /*!<@brief PORT pin mask */
                                                              /* @} */

/*! @name PIO0_17 (coord E1), dac_reset_out
  @{ */
/* Routed pin properties */
#define BOARD_INITPINS_dac_reset_out_PERIPHERAL LVLSHFT        /*!<@brief Peripheral name */
#define BOARD_INITPINS_dac_reset_out_SIGNAL OUT                /*!<@brief Signal name */
#define BOARD_INITPINS_dac_reset_out_CHANNEL 0                 /*!<@brief Signal channel */
#define BOARD_INITPINS_dac_reset_out_PIN_NAME PIO0_17          /*!<@brief Routed pin name */
#define BOARD_INITPINS_dac_reset_out_LABEL "dac_reset_out"     /*!<@brief Label */
#define BOARD_INITPINS_dac_reset_out_NAME "dac_reset_out"      /*!<@brief Identifier */
#define BOARD_INITPINS_dac_reset_out_PORT 0U                   /*!<@brief PORT device index: 0 */
#define BOARD_INITPINS_dac_reset_out_PIN 17U                   /*!<@brief PORT pin number */
#define BOARD_INITPINS_dac_reset_out_PIN_MASK (1U << 17U)      /*!<@brief PORT pin mask */
                                                               /* @} */

/*! @name RESETN (coord C1), resetn
  @{ */
/* Routed pin properties */
#define BOARD_INITPINS_resetn_PERIPHERAL SYSCON        /*!<@brief Peripheral name */
#define BOARD_INITPINS_resetn_SIGNAL RESETN            /*!<@brief Signal name */
#define BOARD_INITPINS_resetn_PIN_NAME RESETN          /*!<@brief Routed pin name */
#define BOARD_INITPINS_resetn_LABEL "resetn"           /*!<@brief Label */
#define BOARD_INITPINS_resetn_NAME "resetn"            /*!<@brief Identifier */
#define BOARD_INITPINS_resetn_PORT 0U                  /*!<@brief PORT device index: 0 */
#define BOARD_INITPINS_resetn_PIN 5U                   /*!<@brief PORT pin number */
#define BOARD_INITPINS_resetn_PIN_MASK (1U << 5U)      /*!<@brief PORT pin mask */
                                                       /* @} */

/*!
 * @brief Configures pin routing and optionally pin electrical features.
 *
 */
void BOARD_InitPins(void); /* Function assigned for the Cortex-M0P */

#if defined(__cplusplus)
}
#endif

/*!
 * @}
 */
#endif /* _PIN_MUX_H_ */

/***********************************************************************************************************************
 * EOF
 **********************************************************************************************************************/
